layout_spectrum: 0.9454291
typography_spectrum: 0.2140858
color:
  saturation: 0.8948769
  lightness: 0.8659207
  brandStrength: 0.9818097
  brandColors:
    - '#030504'
    - '#3E5E8D'
    - '#95AFBF'
    - '#FEE9BB'
    - '#FEA369'
  rhythmicContrast: 0.7582691
name: Sunset Road Entertainment
